$BACKGROUND_PATH = ~/.config/hypr/theme/wallpaperlock.png

# Si se especifica monitor, se debe hacerlo al cambiar wallpaper
wallpaper {
    monitor = 
    path = $BACKGROUND_PATH
    fit_mode = cover
}
